CELL_SIZE = 100
SMALL_CELL_NUMBER = 3
BIG_CELL_NUMBER = 3
GAP = 10
INNER_GAP = 5
THIN = 1
THICK = 6
X_THICKNESS = 4
O_THICKNESS = 4

START_TEXT = ("Willkommen\nbei dem Spiel 'ULTIMATE TIC TAC TOE'.\nKlicken Sie mit der Maus\noder druecken Sie ENTER\n"
)

COLORS = {
    "BACKGROUND": (255, 255, 255),
    "TEXT": (0, 0, 0),
    "SMALL_LINE": (71, 74, 80),
    "BIG_LINE": (0, 0, 0),
    "X": (245, 0, 0),
    "O": (0, 0, 245),
    "ACTIVE": (144, 238, 144)
}

BIG_CELL_SIZE = CELL_SIZE * SMALL_CELL_NUMBER + THIN * (SMALL_CELL_NUMBER - 1) + GAP * 2
GRID_WIDTH = BIG_CELL_SIZE * BIG_CELL_NUMBER + THICK * (BIG_CELL_NUMBER - 1)

WINDOW_WIDTH = BIG_CELL_SIZE * 3
WINDOW_HEIGHT = BIG_CELL_SIZE * 3